theme = "dracula"

[editor]
true-color = true
end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
# character = "┆"

[editor.soft-wrap]
enable = true
